2024-11-09 14:13:40,165 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-09 14:13:40,165 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Configure stats pid to 3120
2024-11-09 14:13:40,165 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from C:\Users\minhq\.config\wandb\settings
2024-11-09 14:13:40,165 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\settings
2024-11-09 14:13:40,165 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'api_key': '***REDACTED***', 'project': 'Fine-tuning bert-base-uncased', 'run_name': 'ft-bert-base-uncased-for-binary-search'}
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_init.py:_log_setup():533] Logging user logs to d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\run-20241109_141340-w57n25bf\logs\debug.log
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_init.py:_log_setup():534] Logging internal logs to d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\run-20241109_141340-w57n25bf\logs\debug-internal.log
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_init.py:_jupyter_setup():479] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000013537A6D2B0>
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_init.py:init():619] calling init triggers
2024-11-09 14:13:40,166 INFO    MainThread:3120 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 2e-05, 'train_batch_size': 16, 'eval_batch_size': 16, 'num_train_epochs': 6, 'weight_decay': 0.01}
2024-11-09 14:13:40,167 INFO    MainThread:3120 [wandb_init.py:init():669] starting backend
2024-11-09 14:13:40,167 INFO    MainThread:3120 [wandb_init.py:init():673] sending inform_init request
2024-11-09 14:13:40,168 INFO    MainThread:3120 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-09 14:13:40,169 INFO    MainThread:3120 [wandb_init.py:init():686] backend started and connected
2024-11-09 14:13:40,173 INFO    MainThread:3120 [wandb_run.py:_label_probe_notebook():1341] probe notebook
2024-11-09 14:13:40,173 INFO    MainThread:3120 [wandb_init.py:init():781] updated telemetry
2024-11-09 14:13:40,242 INFO    MainThread:3120 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-09 14:14:54,757 WARNING MainThread:3120 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 817, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-11-09 14:14:56,461 INFO    Thread-21 (wrapped_target):3120 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Program Files\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:983: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\urllib3\connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\workspace\leetcode-workspace\venv\Lib\site-packages\requests\adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)
2024-11-09 14:28:46,208 INFO    MainThread:3120 [wandb_settings.py:_apply_login():1971] Applying login settings: {}
2024-11-09 14:28:46,217 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Configure stats pid to 3120
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from C:\Users\minhq\.config\wandb\settings
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\settings
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'api_key': '***REDACTED***', 'project': 'Fine-tuning bert-base-uncased', 'run_name': 'ft-bert-base-uncased-for-binary-search'}
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-09 14:28:46,218 INFO    MainThread:3120 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:_log_setup():533] Logging user logs to d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\run-20241109_142846-zglwlw1w\logs\debug.log
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:_log_setup():534] Logging internal logs to d:\workspace\leetcode-workspace\jupyter\RMIT Hackathon 2024\wandb\run-20241109_142846-zglwlw1w\logs\debug-internal.log
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:init():619] calling init triggers
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 2e-05, 'train_batch_size': 16, 'eval_batch_size': 16, 'num_train_epochs': 6, 'weight_decay': 0.01}
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:init():669] starting backend
2024-11-09 14:28:46,219 INFO    MainThread:3120 [wandb_init.py:init():673] sending inform_init request
2024-11-09 14:28:46,222 INFO    MainThread:3120 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-09 14:28:46,223 INFO    MainThread:3120 [wandb_init.py:init():686] backend started and connected
2024-11-09 14:28:46,229 INFO    MainThread:3120 [wandb_run.py:_label_probe_notebook():1341] probe notebook
2024-11-09 14:28:46,230 INFO    MainThread:3120 [wandb_init.py:init():781] updated telemetry
2024-11-09 14:28:46,338 INFO    MainThread:3120 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-09 14:28:46,976 INFO    MainThread:3120 [wandb_init.py:init():867] starting run threads in backend
2024-11-09 14:28:47,202 INFO    MainThread:3120 [wandb_run.py:_console_start():2451] atexit reg
2024-11-09 14:28:47,202 INFO    MainThread:3120 [wandb_run.py:_redirect():2299] redirect: wrap_raw
2024-11-09 14:28:47,203 INFO    MainThread:3120 [wandb_run.py:_redirect():2364] Wrapping output streams.
2024-11-09 14:28:47,203 INFO    MainThread:3120 [wandb_run.py:_redirect():2389] Redirects installed.
2024-11-09 14:28:47,207 INFO    MainThread:3120 [wandb_init.py:init():911] run started, returning control to user process
2024-11-09 14:29:17,591 WARNING MsgRouterThr:3120 [router.py:message_loop():75] message_loop has been closed
